[target.wasm32-wasip1]
runner = ["wasmedge", "--dir", ".", "--dir", "tests/testdir:tests/testdir"]

[build]
target-dir = "target/wasmedge-tco"
rustflags = [
  "-C", "target-feature=+multivalue,+tail-call",
  "-C", "link-arg=-s",
]
