[build]
rustflags = [
  "-C", "target-feature=+bulk-memory,+mutable-globals,+nontrapping-fptoint,+reference-types,+sign-ext",
]

[alias]
test-wasmtime-legacy  = ["test",  "--target", "wasm32-wasip1", "--release", "--features", "wasmtime",     "--config", ".cargo/config-wasmtime-legacy.toml"]
test-wasmtime-tco     = ["test",  "--target", "wasm32-wasip1", "--release", "--features", "wasmtime,tco", "--config", ".cargo/config-wasmtime-tco.toml"]
test-wasmedge-legacy  = ["test",  "--target", "wasm32-wasip1", "--release", "--features", "wasmedge",     "--config", ".cargo/config-wasmedge-legacy.toml"]
test-wasmedge-tco     = ["test",  "--target", "wasm32-wasip1", "--release", "--features", "wasmedge,tco", "--config", ".cargo/config-wasmedge-tco.toml"]
build-wasmtime-legacy = ["build", "--target", "wasm32-wasip1", "--release", "--features", "wasmtime",     "--config", ".cargo/config-wasmtime-legacy.toml"]
build-wasmtime-tco    = ["build", "--target", "wasm32-wasip1", "--release", "--features", "wasmtime,tco", "--config", ".cargo/config-wasmtime-tco.toml"]
build-wasmedge-legacy = ["build", "--target", "wasm32-wasip1", "--release", "--features", "wasmedge",     "--config", ".cargo/config-wasmedge-legacy.toml"]
build-wasmedge-tco    = ["build", "--target", "wasm32-wasip1", "--release", "--features", "wasmedge,tco", "--config", ".cargo/config-wasmedge-tco.toml"]
