[target.wasm32-wasip1]
runner = ["wasmedge", "--dir", ".", "--dir", "tests/testdir:tests/testdir"]

[build]
rustflags = [
  "-C", "target-feature=+bulk-memory,+mutable-globals,+nontrapping-fptoint,+reference-types,+sign-ext",
  "-C", "link-arg=-s",
]