[target.wasm32-wasip1]
runner = ["wasmtime", "--dir", ".", "--dir", "tests/testdir"]

[build]
target-dir = "target/wasmtime-tco"
rustflags = [
  "-C", "target-feature=+multivalue,+tail-call",
  "-C", "link-arg=-s",
]
