name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        target: wasm32-wasip1
        components: rustfmt

    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install wasmtime
      run: |
        curl -L https://github.com/bytecodealliance/wasmtime/releases/download/v35.0.0/wasmtime-v35.0.0-x86_64-linux.tar.xz | tar -xJ
        sudo mv wasmtime-v35.0.0-x86_64-linux/wasmtime /usr/local/bin/
        wasmtime --version
    - name: Build test (wasm32-wasip1)
      run: cargo build --release --verbose --target wasm32-wasip1

    - name: Run tests (wasm32-wasip1)
      run: |
        echo "Running wasm32-wasip1 tests with wasmtime "
        cargo test --verbose --target wasm32-wasip1 --features wasmtime
    
    - name: Check formatting
      run: cargo fmt --all --check

